/*
 * Created By Yugal Kukde
 */
package tqa.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import tqa.DAO.PerformanceDAO;
import tqa.DAO.QuestionDAO;
import tqa.pojo.Answer;
import tqa.pojo.AnswerStore;
import tqa.pojo.Exam;
import tqa.pojo.Performance;
import tqa.pojo.Question;
import tqa.pojo.QuestionStore;
import tqa.pojo.UserProfile;

/**
 *
 * @author YUGAL
 */
public class TakeTestFrame extends javax.swing.JFrame {

    /**
     * Creates new form TakeTestFrame
     */
    private Exam exam;
    Question question;
    private QuestionStore qstore;
    private AnswerStore astore;
    private int qno, pos = 0;

    public TakeTestFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.lblStuName.setText("Hello " + UserProfile.getUserid());
        qstore = new QuestionStore();
        astore = new AnswerStore();
    }

    public TakeTestFrame(Exam exam) {
        this();
        this.exam = exam;
        lblTitle.setText(exam.getLaunguae().toUpperCase() + " Paper");
        loadQuestions();
        showQuestion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblStuName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblQueNo = new javax.swing.JLabel();
        jrOption1 = new javax.swing.JRadioButton();
        jrOption3 = new javax.swing.JRadioButton();
        jrOption2 = new javax.swing.JRadioButton();
        jrOption4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblStuName.setBackground(new java.awt.Color(0, 0, 0));
        lblStuName.setForeground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("JAVA PAPER");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/good luck2.jpg"))); // NOI18N

        lblQueNo.setBackground(new java.awt.Color(0, 0, 0));
        lblQueNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQueNo.setForeground(new java.awt.Color(255, 255, 255));
        lblQueNo.setText("Question 1");

        jrOption1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrOption1);
        jrOption1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrOption1.setForeground(new java.awt.Color(255, 255, 255));
        jrOption1.setSelected(true);
        jrOption1.setText("option1");

        jrOption3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrOption3);
        jrOption3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrOption3.setForeground(new java.awt.Color(255, 255, 255));
        jrOption3.setText("jRadioButton1");

        jrOption2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrOption2);
        jrOption2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrOption2.setForeground(new java.awt.Color(255, 255, 255));
        jrOption2.setText("jRadioButton1");

        jrOption4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrOption4);
        jrOption4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrOption4.setForeground(new java.awt.Color(255, 255, 255));
        jrOption4.setText("jRadioButton1");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PREVIOUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("NEXT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("DONE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtQuestion.setBackground(new java.awt.Color(0, 0, 0));
        txtQuestion.setColumns(20);
        txtQuestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuestion.setForeground(new java.awt.Color(255, 255, 255));
        txtQuestion.setRows(5);
        jScrollPane1.setViewportView(txtQuestion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrOption2)
                            .addComponent(jrOption1)
                            .addComponent(jrOption4)
                            .addComponent(jrOption3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblStuName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316)
                        .addComponent(lblTitle)
                        .addGap(375, 375, 375)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblQueNo)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jButton4)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addGap(43, 43, 43)
                .addComponent(jButton3)
                .addGap(29, 29, 29)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStuName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblTitle))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblQueNo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66)
                .addComponent(jrOption1)
                .addGap(18, 18, 18)
                .addComponent(jrOption2)
                .addGap(18, 18, 18)
                .addComponent(jrOption3)
                .addGap(18, 18, 18)
                .addComponent(jrOption4)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ans = JOptionPane.showConfirmDialog(null, "Logout", "Are You Sure?", JOptionPane.YES_NO_OPTION);
        if (ans == JOptionPane.YES_OPTION) {
            LoginFrame lf = new LoginFrame();
            this.dispose();
            lf.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String choosenOp = getChosenOp();
        if (choosenOp != null) {
            Question question = qstore.getQuestion(pos);
            qno = question.getQno();
            String correctAnswer = question.getCorrectAns();
            Answer newAnswer = new Answer(exam.getExamID(), exam.getLaunguae(), qno, choosenOp, correctAnswer);
            System.out.println(newAnswer);
            Answer answer = astore.getAnswerByQno(qno);
            if (answer == null) {
                astore.addAnswer(newAnswer);
            } else {
                if (newAnswer.getChoosenAnswer().equals(answer.getChoosenAnswer()) == false) {
                    int apos = astore.removeAnswer(answer);
                    astore.setAnswerAt(apos, newAnswer);
                }
            }
        }
        int right = 0, wrong = 0;
        for (Question question1 : qstore.getllQuestion()) {
            int qno = question1.getQno();
            Answer answer = astore.getAnswerByQno(qno);
            if (answer == null) {
                continue;
            } else {
                String chosenAnswer = answer.getChoosenAnswer();
                String correctAnswer = answer.getCorrectAnswer();
                if (chosenAnswer.equals(correctAnswer)) {
                    right++;
                } else if (!chosenAnswer.equals(correctAnswer)) {
                    wrong++;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Total Question =" + qstore.getCount() + "\n" + "Right =" + right + "\n" + "Wrong =" + wrong + "\n" + "Unattempted =" + (qstore.getCount() - (right + wrong)), "Done!!!", JOptionPane.INFORMATION_MESSAGE);
        try {
            Performance perform = new Performance(UserProfile.getUserid(), exam.getExamID(), right, wrong, (qstore.getCount() - (right + wrong)), (double) (right * 100) / qstore.getCount(), exam.getLaunguae());
            PerformanceDAO.addPerformance(perform);
            JOptionPane.showMessageDialog(null, "Your answers have been saved successfully", "Done!!!", JOptionPane.INFORMATION_MESSAGE);
            PaperSelectionFrame psf = new PaperSelectionFrame();
            psf.setVisible(true);
            this.dispose();
        } catch (SQLException sql) {
            JOptionPane.showMessageDialog(null, "SQLException !" + sql, "Exception!", JOptionPane.ERROR_MESSAGE);
            sql.printStackTrace();
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        StudentFrame sf = new StudentFrame();
        this.dispose();
        sf.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String choosenOp = getChosenOp();
        if (choosenOp != null) {
            qno = question.getQno();
            Question question1 = qstore.getQuestion(pos);
            String correctAnswer = question1.getCorrectAns();
            Answer newAnswer = new Answer(exam.getExamID(), exam.getLaunguae(), qno, choosenOp, correctAnswer);
            System.out.println(newAnswer);
            Answer answer = astore.getAnswerByQno(qno);
            if (answer == null) {
                astore.addAnswer(newAnswer);
            } else {
                if (newAnswer.getChoosenAnswer().equals(answer.getChoosenAnswer()) == false) {
                    int apos = astore.removeAnswer(answer);
                    astore.setAnswerAt(apos, newAnswer);
                }
            }
        }
        pos++;
        if (pos >= qstore.getCount()) {
            pos = 0;
        }
        qno++;
        if (qno > qstore.getCount()) {
            qno = 1;
        }
        lblQueNo.setText("Question " + qno);
        showQuestion();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String choosenOp = getChosenOp();
        if (choosenOp != null) {
            qno = question.getQno();
            Question question1 = qstore.getQuestion(pos);
            String correctAnswer = question1.getCorrectAns();
            Answer newAnswer = new Answer(exam.getExamID(), exam.getLaunguae(), qno, choosenOp, correctAnswer);
            System.out.println(newAnswer);
            Answer answer = astore.getAnswerByQno(qno);
            if (answer == null) {
                astore.addAnswer(newAnswer);
            } else {
                if (newAnswer.getChoosenAnswer().equals(answer.getChoosenAnswer()) == false) {
                    int apos = astore.removeAnswer(answer);
                    astore.setAnswerAt(apos, newAnswer);
                }
            }
        }
        pos--;
        if (pos <= qstore.getCount()) {
            pos = 0;
        }
        qno--;
        if (qno < qstore.getCount()) {
            qno = 1;
        }
        lblQueNo.setText("Question " + qno);
        showQuestion();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrOption1;
    private javax.swing.JRadioButton jrOption2;
    private javax.swing.JRadioButton jrOption3;
    private javax.swing.JRadioButton jrOption4;
    private javax.swing.JLabel lblQueNo;
    private javax.swing.JLabel lblStuName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables

    private void loadQuestions() {
        try {
            ArrayList<Question> queList = QuestionDAO.getQuestionsByExamId(exam.getExamID());
            for (Question obj : queList) {
                qstore.addQuestion(obj);
            }
        } catch (SQLException sql) {
            JOptionPane.showMessageDialog(null, "Error while connecting to DB! " + sql, "Exception!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showQuestion() {
        buttonGroup1.clearSelection();
        question = qstore.getQuestion(pos);
        txtQuestion.setText(question.getQuestion());
        jrOption1.setText(question.getAns1());
        jrOption2.setText(question.getAns2());
        jrOption3.setText(question.getAns3());
        jrOption4.setText(question.getAns4());
        Answer answer = astore.getAnswerByQno(qno);
        if (answer == null) {
            return;
        }
        String chosenAnswer = answer.getChoosenAnswer();
        switch (chosenAnswer) {
            case "Ans1":
                jrOption1.setSelected(true);
                break;
            case "Ans2":
                jrOption2.setSelected(true);
                break;
            case "Ans3":
                jrOption3.setSelected(true);
                break;
            case "Ans4":
                jrOption4.setSelected(true);
                break;
        }
    }

    private String getChosenOp() {
        if (jrOption1.isSelected()) {
            return "Ans1";
        } else if (jrOption2.isSelected()) {
            return "Ans2";
        } else if (jrOption3.isSelected()) {
            return "Ans3";
        } else if (jrOption4.isSelected()) {
            return "Ans4";
        } else {
            return null;
        }
    }
}
